name: twitter
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 1-5'
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensaje'     
        required: true
        default: 'Venga, vamos que hoy es viernes, salimos a las 3 y no hay paso a produccion'

jobs:
  check-groovy:
    runs-on: ubuntu-latest
    env:
      GROOVY_VERSION: 3.0.5
      CONSUMERKEY: ${{ secrets.CONSUMERKEY }}
      CONSUMERSECRET: ${{ secrets.CONSUMERSECRET }}
      ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
      ACCESSTOKENSECRET: ${{ secrets.ACCESSTOKENSECRET }}
      MESSAGE: Venga, vamos que hoy es viernes, salimos a las 3 y no hay paso a produccion
    steps:
      - uses: actions/checkout@v2
      - id: install
        shell: bash
        run: |          
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy $GROOVY_VERSION          
          groovy \
            -Dtwitter4j.oauth.consumerKey=${CONSUMERKEY} \
            -Dtwitter4j.oauth.consumerSecret=${CONSUMERSECRET} \
            -Dtwitter4j.oauth.accessToken=${ACCESSTOKEN} \
            -Dtwitter4j.oauth.accessTokenSecret=${ACCESSTOKENSECRET} \
            scripts/twitter.groovy "${{ github.event.inputs.message || env.MESSAGE }}"

